# Generated by Django 3.1 on 2022-06-22 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import support_request.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorRegionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'directorate',
                'verbose_name_plural': 'directorates',
            },
        ),
        migrations.CreateModel(
            name='MyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('other_client', models.CharField(default=None, max_length=30)),
                ('request_category', models.CharField(choices=[('Systems Assurance', 'Systems Assurance'), ('Data Science', 'Data Science')], default='Systems Assurance', max_length=30)),
                ('requested_date_from', models.DateField(validators=[support_request.models.validate_date])),
                ('requested_date_to', models.DateField(validators=[support_request.models.validate_date])),
                ('date_request_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_request_assigned', models.DateTimeField(auto_now=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('allocated_date_from', models.DateField(blank=True, null=True)),
                ('allocated_date_to', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_request.clientlist')),
                ('directorate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support_request.sectorregionlist')),
            ],
        ),
        migrations.AddField(
            model_name='clientlist',
            name='regional_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_request.sectorregionlist'),
        ),
    ]
